export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const ADD_FRIEND_LIST = 'ADD_FRIEND_LIST';
export const ADD_FRIEND_REQUEST_LIST = 'ADD_FRIEND_REQUEST_LIST';

export const RENDER_ROOM = 'RENDER_ROOM';
export const DESTROY_ROOM = 'DESTROY_ROOM';
export const ADD_MEMBER = 'ADD_MEMBER';
export const DELETE_MEMBER = 'DELETE_MEMBER';
export const UPDATE_ROOM_LOCKING_STATUS = 'UPDATE_ROOM_LOCKING_STATUS';

export const ADD_CHAT = 'ADD_CHAT';
